###########################################################################################
## SECRETS REQUIRED:
## - pypi_username : PyPi login credentials to push image
## - pypi_password : PyPi login credentials to push image
###########################################################################################
kind: pipeline
name: default

steps:
  - name: test-python2
    image: python:2.7
    environment:
      PIPES_REDIS_HOST: redis
      PIPES_MEMCACHED_SERVERS: json:["memcached:11211"]
    commands:
      - pip install -U pip setuptools wheel flake8
      - pip install -e .[tests]
      - flake8
      - pytest --cov-config .coveragerc --cov=pypipes --cov-report term-missing .
    when:
      event:
        - push

  - name: test-python3
    image: python:3.7
    environment:
      PIPES_REDIS_HOST: redis
      PIPES_MEMCACHED_SERVERS: json:["memcached:11211"]
    commends:
      - pip install -U pip setuptools wheel flake8
      - pip install -e .[tests]
      - flake8
      - pytest --cov-config .coveragerc --cov=pypipes --cov-report term-missing .
    when:
      event:
        - push

  - name: dist
    image: python:3.7
    environment:
      PYPI_USERNAME:
        from_secret: pypi_username
      PYPI_PASSWORD:
        from_secret: pypi_password
    commands:
      - pip install twine
      - mkdir dist
      - git fetch --tags
      - python setup.py sdist
      - twine upload dist/pypipes-${DRONE_TAG}.zip -u $PYPI_USERNAME -p $PYPI_PASSWORD
    when:
      event:
        - tag

services:
  - name: redis
    image: redis:4.0.10
  - name: memcached
    image: memcached:1.4.34
