version: '3.1'

services:

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - back-tier

  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
    networks:
      - back-tier

networks:
  back-tier: